enabled: true
ping_offset: 0

enable_message: "&aSuccessfully enabled ValedKnockbackSync."
disable_message: "&cSuccessfully disabled ValedKnockbackSync."
configure_offset_message: "&aSuccessfully configured the ping offset."