name: ValedKnockbackSync
version: '1.3'
main: me.caseload.knockbacksync.KnockbackSync
api-version: '1.18'
authors: [ Caseload, Valed Development Team ]
description: Developed by Valed Development Team, a fork of the knockback-sync plugin by CASELOAD7000.
